@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label class="block text-sm font-medium text-gray-700">Branch</label><select name="branch_id" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $expense->branch_id ?? '') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select>@include('products.partials.field-error', ['name' => 'branch_id'])</div>
    <div><label class="block text-sm font-medium text-gray-700">Category</label><select name="expense_category_id" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('expense_category_id', $expense->expense_category_id ?? '') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>@include('products.partials.field-error', ['name' => 'expense_category_id'])</div>
    <div><label class="block text-sm font-medium text-gray-700">Date</label><input name="expense_date" type="date" value="{{ old('expense_date', isset($expense) ? $expense->expense_date->format('Y-m-d') : now()->toDateString()) }}" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"></div>
    <div><label class="block text-sm font-medium text-gray-700">Amount</label><input name="amount" type="number" step="0.01" min="0.01" value="{{ old('amount', $expense->amount ?? '') }}" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">@include('products.partials.field-error', ['name' => 'amount'])</div>
    <div><label class="block text-sm font-medium text-gray-700">Payment Method</label><select name="payment_method" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">@foreach(['cash','card','bkash','nagad','bank'] as $method)<option value="{{ $method }}" @selected(old('payment_method', $expense->payment_method ?? '') === $method)>{{ ucfirst($method) }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium text-gray-700">Reference No</label><input name="reference_no" value="{{ old('reference_no', $expense->reference_no ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"></div>
    <div class="md:col-span-2"><label class="block text-sm font-medium text-gray-700">Description</label><textarea name="description" rows="3" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">{{ old('description', $expense->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Save</button><a href="{{ route('expenses.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">Cancel</a></div>
